type: xlam

input: src
output: Terra.xlam

tags:
    name: Terra Add-in
    author: Andy Terra
    e-mail: andy@andyterra.com
    website: https://excel.andyterra.com
    version: 0.4

ribbon:
    Terra:
        type: normal # optional, default: normal
        keytip: /
        after: TabView

    Terra Chart:
        type: chart
        keytip: .
        label: Terra # optional, default: same as group name

