from ribbon import customUI14base

class BaseElement(object):
    """Defines common properties to extend autogenerated classes"""
    name = None

    def export(self, *args, **kwargs):
        kwargs.update({
            'name_': self.name,
        })
        super(BaseElement, self).export(*args, **kwargs)

class Root(BaseElement, customUI14base.CT_CustomUI):
    """Defines the root-level customUI tag for customUI14.xml"""

    name = 'customUI'

    def __init__(self, onLoad=None, loadImage=None, commands=None, ribbon=None,
        backstage=None, contextMenus=None, **kwargs):
        super(Root, self).__init__(onLoad, loadImage, commands, ribbon,
            backstage, contextMenus, **kwargs)
        self.ns_prefix_ = ""
    
    def export(self, *args, **kwargs):
        kwargs.update({
            'namespacedef_': 'xmlns="http://schemas.microsoft.com/office/2009/07/customui"',
        })
        super(Root, self).export(*args, **kwargs)

class Ribbon(BaseElement, customUI14base.CT_Ribbon):
    name = 'ribbon'

    def __init__(self, startFromScratch=None, qat=None, tabs=None, contextualTabs=None,
        **kwargs):
        super(Ribbon, self).__init__(startFromScratch, qat, tabs, contextualTabs,
            **kwargs)

class Group(customUI14base.CT_Group):
    """Specifies a single group"""

    name = 'group'

    def __init__(self, autoScale=None, centerVertically=None, id=None, idQ=None, tag=None,
        idMso=None, label=None, getLabel=None, image=None, imageMso=None, getImage=None,
        insertAfterMso=None, insertBeforeMso=None, insertAfterQ=None, insertBeforeQ=None,
        screentip=None, getScreentip=None, supertip=None, getSupertip=None, visible=None,
        getVisible=None, keytip=None, getKeytip=None, control=None, labelControl=None,
        button=None, toggleButton=None, checkBox=None, editBox=None, comboBox=None,
        dropDown=None, gallery=None, menu=None, dynamicMenu=None, splitButton=None,
        box=None, buttonGroup=None, separator=None, dialogBoxLauncher=None, **kwargs):
        super(Group, self).__init__(autoScale, centerVertically, id, idQ, tag,
            idMso, label, getLabel, image, imageMso, getImage, insertAfterMso,
            insertBeforeMso, insertAfterQ, insertBeforeQ, screentip, getScreentip,
            supertip, getSupertip, visible, getVisible, keytip, getKeytip, control,
            labelControl, button, toggleButton, checkBox, editBox, comboBox, dropDown,
            gallery, menu, dynamicMenu, splitButton, box, buttonGroup, separator,
            dialogBoxLauncher,  **kwargs)

class Tabs(customUI14base.CT_Tabs):
    """Specifies a collection of regular tabs"""

    name = 'tabs'

    def __init__(self, tab=None, **kwargs):
        super(Tabs, self).__init__(tab,  **kwargs)

class ContextualTabs(customUI14base.CT_ContextualTabs):
    """Specifies a collection of contextual tabs such as Chart tabs"""

    def __init__(self, tabSet=None, **kwargs):
        super(ContextualTabs, self).__init__(tabSet,  **kwargs)

class Tab(customUI14base.CT_Tab):
    """Specifies a single tab"""

    def __init__(self, id=None, idQ=None, tag=None, idMso=None, label=None,
        getLabel=None, insertAfterMso=None, insertBeforeMso=None, insertAfterQ=None,
        insertBeforeQ=None, visible=None, getVisible=None, keytip=None, getKeytip=None,
        group=None, **kwargs):
        super(Tab, self).__init__(id, idQ, tag, idMso, label, getLabel,
            insertAfterMso, insertBeforeMso, insertAfterQ, insertBeforeQ, visible,
            getVisible, keytip, getKeytip, group,  **kwargs)

class ButtonRegular(BaseElement, customUI14base.CT_ButtonRegular):
    """Specifies a regular button"""

    name = 'button'
    template_callback = """
    Sub call{fun}(control as IRibbonControl)
        Call {fun}
    End Sub
    """

    def __init__(self, image=None, imageMso=None, getImage=None, screentip=None, 
        getScreentip=None, supertip=None, getSupertip=None, enabled=None,
        getEnabled=None, label=None, getLabel=None, insertAfterMso=None, 
        insertBeforeMso=None, insertAfterQ=None, insertBeforeQ=None, visible=None,
        getVisible=None, keytip=None, getKeytip=None, showLabel=None,
        getShowLabel=None, showImage=None, getShowImage=None, id=None, idQ=None,
        tag=None, idMso=None, onAction=None, description=None, getDescription=None,
        extensiontype_=None, **kwargs):
        super(ButtonRegular, self).__init__(image, imageMso, getImage, screentip,
            getScreentip, supertip, getSupertip, enabled, getEnabled, label, getLabel,
            insertAfterMso, insertBeforeMso, insertAfterQ, insertBeforeQ, visible,
            getVisible, keytip, getKeytip, showLabel, getShowLabel, showImage,
            getShowImage, id, idQ, tag, idMso, onAction, description, getDescription,
            extensiontype_,  **kwargs)


class Separator(BaseElement, customUI14base.CT_Separator):
    """Specifies a ribbon separator"""
    
    name = 'separator'

    def __init__(self, id=None, idQ=None, tag=None, visible=None, getVisible=None,
        insertAfterMso=None, insertBeforeMso=None, insertAfterQ=None, insertBeforeQ=None,
        **kwargs):
        super(Separator, self).__init__(id, idQ, tag, visible, getVisible, insertAfterMso,
            insertBeforeMso, insertAfterQ, insertBeforeQ,  **kwargs)
